version: '2'
services:
  gpnode3:
     image: 10.0.0.96:5000/database/gp_43:v1 
     hostname: sdw3
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=100
     networks: 
       - docker_gwbridge
     ports:
       - "20080:40000"
       - "20081:40001"
     volumes:
       - /opt/gpnode3/gpdata_43:/home/gpadmin/gpdata
     privileged: true
     tty: true

